$primary = rgb(e4678e)
$surface = rgb(29141a)
$secondary = rgb(d6745c)
$error = rgb(be5d7b)
$tertiary = rgb(ccac66)
$surface_lowest = rgb(150a0d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
