color0 #29141a
color1 #be5d7b
color2 #e4678e
color3 #d6745c
color4 #ccac66
color5 #ec93af
color6 #e9a696
color7 #f3f2f2
color8 #756167
color9 #be5d7b
color10 #e4678e
color11 #d6745c
color12 #ccac66
color13 #ec93af
color14 #e9a696
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141a
background            #29141a
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #371b23
active_border_color   #e4678e
inactive_border_color #371b23
url_color             #e4678e

active_tab_foreground   #25181c
active_tab_background   #e4678e
inactive_tab_foreground #b6afb1
inactive_tab_background #371b23
cursor_trail_color      #b6afb1
