$background = 0c0003
$onBackground = ffdde4
$surface = 0c0003
$surfaceDim = 0c0003
$surfaceBright = 24000d
$surfaceContainerLowest = 000000
$surfaceContainerLow = 110005
$surfaceContainer = 170007
$surfaceContainerHigh = 1c0009
$surfaceContainerHighest = 20000b
$onSurface = ffdde4
$surfaceVariant = 20000b
$onSurfaceVariant = d89aab
$outline = 9d6675
$outlineVariant = 693948
$inverseSurface = fff8f8
$inverseOnSurface = 784655
$shadow = 000000
$scrim = 000000
$surfaceTint = 480f17
$primary = ff8c94
$primaryDim = ff6f7c
$onPrimary = 640018
$primaryContainer = ff7480
$onPrimaryContainer = 4e0011
$inversePrimary = b4253d
$primaryFixed = ff7480
$primaryFixedDim = fc5b6d
$onPrimaryFixed = 000000
$onPrimaryFixedVariant = 600017
$secondary = f97ea6
$secondaryDim = ef779e
$onSecondary = 550028
$secondaryContainer = 822047
$onSecondaryContainer = ffbfd0
$secondaryFixed = ffc1d1
$secondaryFixedDim = ffadc4
$onSecondaryFixed = 690935
$onSecondaryFixedVariant = 8f2a51
$tertiary = bf9cff
$tertiaryDim = b38cf9
$onTertiary = 3d0d7d
$tertiaryContainer = b38cf9
$onTertiaryContainer = 2f006a
$tertiaryFixed = c2a0ff
$tertiaryFixedDim = b68ffc
$onTertiaryFixed = 22004f
$onTertiaryFixedVariant = 481e89
$error = ff7351
$errorDim = d53d18
$onError = 450900
$errorContainer = b92902
$onErrorContainer = ffd2c8
$primaryPaletteKeyColor = d63f53
$secondaryPaletteKeyColor = c05178
$tertiaryPaletteKeyColor = 8862cb
$neutralPaletteKeyColor = 9f6777
$neutralVariantPaletteKeyColor = a96277
$errorPaletteKeyColor = d9401b
$primary_paletteKeyColor = d63f53
$secondary_paletteKeyColor = c05178
$tertiary_paletteKeyColor = 8862cb
$neutral_paletteKeyColor = 9f6777
$neutral_variant_paletteKeyColor = a96277
$term0 = 080808
$term1 = ff5261
$term2 = ffbca9
$term3 = ffdfd9
$term4 = b3a2d5
$term5 = ef8f9b
$term6 = ffba93
$term7 = efd2cc
$term8 = b49e9a
$term9 = ff8487
$term10 = ffd4c8
$term11 = fff1ee
$term12 = dcbc93
$term13 = fea7af
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffeeed
$flamingo = ffd9d9
$pink = ffd2d8
$mauve = ffa7bf
$red = ff96a0
$maroon = f8aaaf
$peach = ffbeb8
$yellow = ffedea
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = fea0cb
$lavender = ffb9d2
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cb5b7c
$kvisitedSelection = cc5b7c
$knegative = ec5163
$knegativeSelection = ec5163
$kneutral = ff8882
$kneutralSelection = ff8882
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = ffdde4
$subtext1 = d89aab
$subtext0 = 9d6675
$overlay2 = 2b1019
$overlay1 = 270e16
$overlay0 = 240a13
$surface2 = 1f070f
$surface1 = 19040b
$surface0 = 100104
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
