#exec-once = waybar &
exec-once = hyprpaper
exec-once =  noctalia
#exec-once = qs -c caelestia
exec-once = hyprctl setcursor Emo 24
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
#exec-once = eval $(gnome-keyring-daemon --start --components=secrets)
exec-once = sh -c 'sleep 2 && signal-desktop --start-in-tray'
exec-once = wayscriber -d
exec-once = easyeffects --gapplication-service
exec-once = hyprswitch init --show-title &
