##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#browser
windowrule = workspace 2, match:class firefox

#terminal
windowrule = workspace 3, match:class kitty
windowrule = opacity 0.85, match:class kitty

#file manager
windowrule = workspace 4, match:class thunar
windowrule = opacity 0.85, match:class thunar 

#spotify
windowrule = workspace 5, match:class spotify
windowrule = opacity 0.85, match:class spotify


windowrule = workspace 6, match:class net.lutris.Lutris
windowrule = workspace 7, match:class org.kde.okular

windowrule = match:class signal, float on
windowrule = match:class signal, center on
windowrule = match:class signal, size 800 600
